# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_text',
            new_name='pub_date',
        ),
    ]
