# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 02:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_about_handson', models.TextField(blank=True, default='')),
                ('difficult_points', models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('difficult_other', models.TextField(blank=True, default='')),
                ('time_settings', models.CharField(choices=[('too long', '長すぎる'), ('long', '長い'), ('just right', 'ちょうど良い'), ('short', '短い'), ('too short', '短すぎる')], max_length=16)),
                ('handson_level', models.CharField(choices=[('too difficult', '難しすぎる'), ('difficult', '難しい'), ('understand', '理解できた'), ('easy', '易しい'), ('too easy', '易しすぎる')], max_length=16)),
                ('handson_interest', models.CharField(choices=[('overall', '全体的に知りたい内容を含んでいた'), ('some', '一部知りたい内容を含んでいた'), ('thin', '興味関心が薄い分野だった')], max_length=8)),
                ('handson_quantity', models.CharField(choices=[('too many', '項目が多すぎる'), ('many', '項目が多い'), ('just right', 'ちょうど良い'), ('short', '項目が少ない'), ('too short', '項目が少なすぎる')], max_length=16)),
                ('free_opinions', models.TextField(blank=True, default='')),
                ('interest_trainings', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
